### ISSUE TITLE
[Service] RAKIP Model Curation

### ISSUE THREAD

**Issue by schuelet** [KIDA-BfR/App-Development#10]
**RAKIP Model Curation**

**Code Base**

URL to the code if available

**Developers**
Racem, Petra

# App Information

**App Status**
- [x] in active development
- [ ] maintenance
- [ ] end of support
- [ ] end of life

## TODO's
- [ ] tutorials/ installation guide
- [ ] SOP
- [ ] sufficient presence on foodrisklabs website (step-by-step guide for customers)

## Findability & Accessibility TODO's
- [ ] hosted by service: < Hosting Service >
- [ ] on foodrisklabs website < URL > 
- [ ] API available here: < endpoint > 
- [ ] Frontend Web-Service available here: < URL > 
- [ ] in a public repository: < URL >

**Additional notes**
